---
- name: Install tree
  hosts: all
  become: yes

  tasks:
    - name: Install tree
      apt:
        name: tree
        state: present

    - name: Start service
      service:
        name: tree
        state: started
        enabled: yes
...          
