---
- name: install and verify the apache2
  hosts: test-vms
  become: yes
  tasks:
    - name: Install apache2
      apt:
        mame: apache2
        state: absent
        update:_cache: yes
    - name: edit the conifg file
      copy:
        content: "Welcome ashok"
        dest: /var/www/html/index.html
    - name: restart apache2
      service:
        name: apache2
        state: restarted
    - name: verify the url access or not
      uri:
        url: http://192.168.124.143
          #url: http://192.168.124.99
        status_code: 200
...
