---
- name: to remove apache application
  hosts: all # to all hosts in the inventory file
  become: yes

  tasks:

    - name: install paache
      apt:
        name: apache2
        state: absent
        update_cache: yes
...
